"""Criando tabelas iniciais cliente_mensagem

Revision ID: 888e7d557311
Revises: 
Create Date: 2026-02-22 03:31:22.853449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '888e7d557311'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('whatsapp_id', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_whatsapp_id'), 'clientes', ['whatsapp_id'], unique=True)
    op.create_table('mensagens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('id_cliente', sa.String(length=36), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('mensagem_id_whatsapp', sa.String(length=200), nullable=True),
    sa.Column('direcao', sa.String(length=10), nullable=True),
    sa.Column('data_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_id_cliente'), 'mensagens', ['id_cliente'], unique=False)
    op.create_index(op.f('ix_mensagens_mensagem_id_whatsapp'), 'mensagens', ['mensagem_id_whatsapp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensagens_mensagem_id_whatsapp'), table_name='mensagens')
    op.drop_index(op.f('ix_mensagens_id_cliente'), table_name='mensagens')
    op.drop_table('mensagens')
    op.drop_index(op.f('ix_clientes_whatsapp_id'), table_name='clientes')
    op.drop_table('clientes')
    # ### end Alembic commands ###
